# This is a basic workflow to help you get started with Actions

name: Deploy Project to Surge

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Setup Surge
        run: npm install --global surge
      
      #deploy App to surge
      - name: Deploying Surge
        run: surge ./ mujahidhassan_jsprojects.surge.sh --token ${{ secrets.SURGE_TOKEN }}




